"""Change id column to BigInteger

Revision ID: 9dbb02a389c4
Revises: bf396091c5e0
Create Date: 2025-11-03 13:20:51.937513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9dbb02a389c4'
down_revision: Union[str, Sequence[str], None] = 'bf396091c5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_table('emails')
    op.drop_table('refresh_meta')
    op.alter_column('issues', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('issues', 'issue_id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'issue_id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('issues', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('refresh_meta',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_countries', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_refreshed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('emails',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('sender', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('snippet', mysql.TEXT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('countries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('capital', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('currency_code', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('exchange_rate', mysql.FLOAT(), nullable=True),
    sa.Column('estimated_gdp', mysql.FLOAT(), nullable=True),
    sa.Column('flag_url', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('last_refreshed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('tokens',
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('token_json', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
